### ISSUE TITLE
Use mime instead of mime-types for compatibility with Obsidian mobile

### ISSUE THREAD

**Issue by mardukbp** [kxxt/obsidian-advanced-paste#11]
mime-types depends on the NodeJS library `path`. And NodeJS APIs are not available in Obsidian mobile. Therefore "Advanced Paste for Obsidian" crashes while loading on a mobile device. 

The [mime](https://www.npmjs.com/package/mime) library does not have any dependency on NodeJS.

I switched the libraries, compiled the plugin and now it starts on my Android phone. I tested it with text/plain in the clipboard.

Thank you for developing this awesome plugin! Now I have cross-vault links :)

**Comment by kxxt** [comment]
Thanks! I have fixed it in v2.5.0.

It is nice to hear that you find a great way to use my plugin.

**Comment by mardukbp** [comment]
Awesome! Thanks for the quick fix :)
