### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by ricecakebear** [kxxt/obsidian-advanced-paste#4]
It stuck at the condition of the following code:
https://github.com/kxxt/obsidian-advanced-paste/blob/e2a31a4e4a6658afc89706e83b45a6841937a6b5/src/main.ts#L42

**Comment by kxxt** [comment]
Hi @ricecakebear, thank you for trying out this plugin on mobile. 

I haven't tested my plugin on mobile as I usually only use obsidian on desktop.

I will take a look at this bug when I have time.

**Comment by kxxt** [comment]
It should be fixed in v2.0.3.
