### ISSUE TITLE
README comment on tables is confusing

### ISSUE THREAD

**Issue by spiritualgeek** [kxxt/obsidian-advanced-paste#6]
> Obsidian's built-in paste function also uses turndown, but it doesn't use the [turndown-plugin-gfm](https://github.com/mixmark-io/turndown-plugin-gfm) plugin, _**which means that it doesn't support converting html tables to markdown tables**_, html task lists to markdown task lists, etc.

The example shows this working, or am I misunderstanding this comment?

**Comment by kxxt** [comment]
Thanks for pointing it out. I have updated the README to make it more clear.
