### ISSUE TITLE
Breaks paste in Search field

### ISSUE THREAD

**Issue by luckman212** [kxxt/obsidian-advanced-paste#7]
Thanks for this plugin!

Just a quick report: if bound to <kbd>⌘ + V</kbd>, it breaks paste function when trying to paste a string into the Search field. Not sure if there is any way to detect & work around that.

**Comment by kxxt** [comment]
Thanks for your bug report! I will look for workarounds.In the mean time You can try binding the command to other shortcuts to avoid this bug.

**Comment by kxxt** [comment]
Fixed in v2.3.1. Please unbind `⌘ + V`.  The default paste command now just works.

**Comment by luckman212** [comment]
Awesome - I will give it a try, thank you!

**Comment by luckman212** [comment]
@kxxt I forgot to mention, I'm on a Mac. I don't think this is working because on macOS, the default paste hotkey is <kbd>Command (⌘) + V</kbd>. When I enabled the new feature and tried it, it did not trigger Advanced Paste. I had to revert back to the previous method.

**Comment by kxxt** [comment]
@luckman212  Did you restarted obsidian after updating the plugin? It should work on Mac despite the keyboard shortcut is  `⌘V`.

See the release note for more info: https://github.com/kxxt/obsidian-advanced-paste/releases/tag/2.3.1

If it still not works, please attach an screenshot of the console. (`View` > `Toggle Developer Tools`)

**Comment by luckman212** [comment]
I re-tested it a few times (yes I restarted Obsidian each time)

It's not working for me (?)

Screenshots:

![image](https://github.com/kxxt/obsidian-advanced-paste/assets/1992842/89fbbef2-a4b4-4358-a29b-ad09258d7a11)

![image](https://github.com/kxxt/obsidian-advanced-paste/assets/1992842/a847dab3-48d4-4144-8ac8-4ee65833161e)

![image](https://github.com/kxxt/obsidian-advanced-paste/assets/1992842/97d6b23d-2e9c-4f04-9dc5-0cb2192caa73)

**Comment by kxxt** [comment]
@luckman212  Can you test it in a sandbox? 

![image](https://github.com/kxxt/obsidian-advanced-paste/assets/18085551/bb438491-76d0-4ca7-b391-86f7ddb2b747)

I guess some other plugins handled the paste event so my plugin can't handle it.

**Comment by luckman212** [comment]
I made a dumb mistake. Sorry!

I was thinking (why??) that Ctrt/Cmd+V would trigger my custom transform.js. Oops.

It works fine with the normal behavior. Hope I didn't waste too much of your time 😔

**Comment by kxxt** [comment]
No need to say sorry. We all make mistakes from time to time. :)
